### ISSUE TITLE
Build fails with llvm-19 on Fedora

### ISSUE THREAD

**Issue by junghans** [lfortran/lfortran#5703]
From https://koji.fedoraproject.org/koji/taskinfo?taskID=126857622:
```
[ 96%] Linking CXX executable test_stacktrace
cd /builddir/build/BUILD/lfortran-0.41.0-build/lfortran-0.41.0/redhat-linux-build/src/lfortran/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_stacktrace.dir/link.txt --verbose=1
/usr/bin/g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DNDEBUG -Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes CMakeFiles/test_stacktrace.dir/test_stacktrace.cpp.o -o test_stacktrace  ../liblfortran_lib.a ../../libasr/libasr.a ../../runtime/legacy/liblfortran_runtime_static.a -lbfd /usr/lib64/libLLVMMCJIT.a /usr/lib64/libLLVMOrcJIT.a /usr/lib64/libLLVMExecutionEngine.a /usr/lib64/libLLVMRuntimeDyld.a /usr/lib64/libLLVMPasses.a /usr/lib64/libLLVMCoroutines.a /usr/lib64/libLLVMHipStdPar.a /usr/lib64/libLLVMipo.a /usr/lib64/libLLVMFrontendOpenMP.a /usr/lib64/libLLVMFrontendOffloading.a /usr/lib64/libLLVMLinker.a /usr/lib64/libLLVMVectorize.a /usr/lib64/libLLVMJITLink.a /usr/lib64/libLLVMOrcTargetProcess.a /usr/lib64/libLLVMOrcShared.a /usr/lib64/libLLVMWindowsDriver.a /usr/lib64/libLLVMOption.a /usr/lib64/libLLVMX86CodeGen.a /usr/lib64/libLLVMAsmPrinter.a /usr/lib64/libLLVMCFGuard.a /usr/lib64/libLLVMGlobalISel.a /usr/lib64/libLLVMIRPrinter.a /usr/lib64/libLLVMInstrumentation.a /usr/lib64/libLLVMSelectionDAG.a /usr/lib64/libLLVMCodeGen.a /usr/lib64/libLLVMTarget.a /usr/lib64/libLLVMBitWriter.a /usr/lib64/libLLVMScalarOpts.a /usr/lib64/libLLVMAggressiveInstCombine.a /usr/lib64/libLLVMInstCombine.a /usr/lib64/libLLVMObjCARCOpts.a /usr/lib64/libLLVMTransformUtils.a /usr/lib64/libLLVMAnalysis.a /usr/lib64/libLLVMProfileData.a /usr/lib64/libLLVMSymbolize.a /usr/lib64/libLLVMDebugInfoPDB.a /usr/lib64/libLLVMDebugInfoMSF.a /usr/lib64/libLLVMDebugInfoBTF.a /usr/lib64/libLLVMDebugInfoDWARF.a /usr/lib64/libLLVMObject.a /usr/lib64/libLLVMIRReader.a /usr/lib64/libLLVMAsmParser.a /usr/lib64/libLLVMBitReader.a /usr/lib64/libLLVMCore.a /usr/lib64/libLLVMRemarks.a /usr/lib64/libLLVMTextAPI.a /usr/lib64/libLLVMBitstreamReader.a /usr/lib64/libLLVMX86AsmParser.a /usr/lib64/libLLVMX86Desc.a /usr/lib64/libLLVMCodeGenTypes.a /usr/lib64/libLLVMMCParser.a /usr/lib64/libLLVMX86Disassembler.a /usr/lib64/libLLVMX86Info.a /usr/lib64/libLLVMMCDisassembler.a /usr/lib64/libLLVMMC.a /usr/lib64/libLLVMBinaryFormat.a /usr/lib64/libLLVMTargetParser.a /usr/lib64/libLLVMDebugInfoCodeView.a /usr/lib64/libLLVMSupport.a /usr/lib64/libz.a /usr/lib64/libLLVMDemangle.a -lrt -ldl -lm /usr/lib64/libzstd.so
/usr/bin/ld: ../../libasr/libasr.a(string_utils.cpp.o): in function `std::ctype<char>::widen(char) const':
/usr/include/c++/14/bits/locale_facets.h:885:(.text+0x9ca): undefined reference to `std::ctype<char>::do_widen(char) const'
/usr/bin/ld: /usr/include/c++/14/bits/locale_facets.h:885:(.text+0x37ff): undefined reference to `std::ctype<char>::do_widen(char) const'
/usr/bin/ld: ../../libasr/libasr.a(string_utils.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/usr/include/c++/14/bits/basic_string.h:809:(.text.unlikely+0x46): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()'
/usr/bin/ld: ../../libasr/libasr.a(string_utils.cpp.o): in function `LCompilers::slice(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int, int)':
/builddir/build/BUILD/lfortran-0.41.0-build/lfortran-0.41.0/src/libasr/string_utils.cpp:122:(.text.unlikely+0x17e): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'
```

**Comment by certik** [comment]
I think you need to upgrade LFortran to the latest release. It should work. Also the above error seems like some kind of C++ error.

**Comment by junghans** [comment]
I rebuild with v0.42.0, but same result: https://koji.fedoraproject.org/koji/taskinfo?taskID=126887211

**Comment by junghans** [comment]
llvm18 works though.

**Comment by junghans** [comment]
As it works with llvm-19 on conda, it must some Fedora specific thing @nikic @kwk any ideas?

**Comment by nikic** [comment]
Duplicate of https://github.com/lfortran/lfortran/issues/5072. The conclusion there is that there is probably a mismatch in the targeted C++ version somewhere, but it's unclear where.

**Comment by junghans** [comment]
Duplicate of #5072
