### ISSUE TITLE
C: Integration tests fail on Mac

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#4047]
```console
CMakeFiles/matmul_01.dir/matmul_01.f90.o.tmp.c:62:5: error: call to undeclared function '_lfortran_d_cpu_time'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    _lfortran_d_cpu_time(&(*t));
    ^
CMakeFiles/matmul_01.dir/matmul_01.f90.o.tmp.c:62:5: note: did you mean '_lfortran_cpu_time'?
/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/../libasr/runtime/lfortran_intrinsics.h:223:19: note: '_lfortran_cpu_time' declared here
LFORTRAN_API void _lfortran_cpu_time(double *t);
                  ^
1 error generated.
The command 'gcc  -I/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/../libasr/runtime -o CMakeFiles/matmul_01.dir/matmul_01.f90.o -c CMakeFiles/matmul_01.dir/matmul_01.f90.o.tmp.c' failed.
make[2]: *** [CMakeFiles/matmul_01.dir/build.make:75: CMakeFiles/matmul_01.dir/matmul_01.f90.o] Error 11
make[1]: *** [CMakeFiles/Makefile2:2019: CMakeFiles/matmul_01.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This seems a bit flaky as I can see the error in some runs/builds and sometimes not. Strangely, this does not get caught at the CI (https://github.com/lfortran/lfortran/actions/runs/9162461783/job/25189524258):

```console
CMakeFiles/matmul_01.dir/matmul_01.f90.o.tmp.c: In function ‘sp_cpu_time’:
CMakeFiles/matmul_01.dir/matmul_01.f90.o.tmp.c:62:5: warning: implicit declaration of function ‘_lfortran_d_cpu_time’; did you mean ‘_lfortran_cpu_time’? [-Wimplicit-function-declaration]
   62 |     _lfortran_d_cpu_time(&(*t));
      |     ^~~~~~~~~~~~~~~~~~~~
      |     _lfortran_cpu_time
```

Introduced in https://github.com/lfortran/lfortran/pull/3920
