### ISSUE TITLE
itpplasma/spline: OpenMP sentinels + LAPACK (dptsv) external resolution/mangling

### ISSUE THREAD

**Issue by krystophny** [lfortran/lfortran#9446]
## Summary
`itpplasma/spline` does not currently build cleanly with LFortran `main` due to a sequence of blockers:
1) `!$omp threadprivate(...)` is treated as an OpenMP pragma even when OpenMP is not enabled.
2) After the OpenMP-sentinel parsing problem is addressed, `dptsv` (LAPACK) is rejected unless implicit interfaces are enabled.
3) Even with `--implicit-interface` and `-llapack -lblas`, linking fails because LFortran calls `dptsv` (no underscore) while system LAPACK typically exports `dptsv_`.

We are tracking this as part of compiling ITP Plasma codes (`spline` and `vode` first).

## Environment
- LFortran: `ef70dd43011b30b006d758c1c114b19c47d24fb3` (`upstream/main` as of 2026-01-10)
- Reproducer: `itpplasma/spline` @ `1c40553a2cc6c930804cc8ea9cc9393106345a6e`

## Reproducer
```bash
git clone https://github.com/itpplasma/spline.git
cd spline

# 1) OpenMP sentinels should be ignored when OpenMP is off
lfortran spline.f90

# 2) After OpenMP sentinel handling is fixed/ignored, compilation proceeds to LAPACK call
#    but LFortran requires either explicit interface or --implicit-interface:
#
# lfortran spline.f90 spline_test.f90
#   semantic error: Function 'dptsv' not found (not user defined nor intrinsic)

# 3) With implicit interfaces and system LAPACK/BLAS:
lfortran spline.f90 spline_test.f90 --implicit-interface -llapack -lblas -o spline_test_lfortran
#   /usr/bin/ld: ... undefined reference to `dptsv'
```

### (1) OpenMP sentinels
```
syntax error: Token '!$omp threadprivate(j_start)' (of type 'pragma') is unexpected here
 --> spline.f90:9:3
```

### (3) Link error against system LAPACK
```
/usr/bin/ld: ... undefined reference to `dptsv'
```

## Evidence for underscore mismatch
- System LAPACK exports `dptsv_`, not `dptsv`.
- LFortran currently references `dptsv` (no underscore) from generated objects.

(Concrete nm output:)

```
# System LAPACK provides dptsv_ (trailing underscore)
0000000000272780 T dptsv_

# LFortran-generated object references
                 U dptsv
```

## Related PRs
- https://github.com/lfortran/lfortran/pull/9444 (treat OpenMP sentinels as comments unless `--openmp`)

## Related
- OpenMP sentinel directives when OpenMP is off: #6449
- LAPACK tracking: #5482
- External/implicit-interface policy for procedure calls: #1170
- External subroutine not found (similar symptom): #6623
- Underscore/mangling discussion and flags (`--mangle-underscore`, `--separate-compilation`): #9067
- External BLAS/LAPACK + implicit interface corner cases (examples): #4251, #2924

## Notes / desired behavior
- Current workaround for users: provide an explicit interface/wrapper for `dptsv` (e.g. via `iso_c_binding` and `bind(C, name="dptsv_")`) or use a LAPACK built with the expected symbol names.
- `--mangle-underscore` currently does not affect the emitted external symbol for this LAPACK call (object still references `dptsv`).
- Without `--openmp`, OpenMP sentinels like `!$omp ...` should be treated as comments.
- For LAPACK/BLAS calls, either:
  - `--mangle-underscore` should also apply to external procedure calls so `dptsv` resolves as `dptsv_`, or
  - provide a documented/robust alternative path (e.g., recommended `iso_c_binding` wrapper pattern) that works for common system BLAS/LAPACK.

**Comment by krystophny** [comment]
Extra notes after digging into related issues/comments:

- The OpenMP-sentinel failure is exactly the behavior described in #6449 (should be ignored without `--openmp`). In `spline.f90` it is:
  - `spline.f90:9`: `!$omp threadprivate(j_start)`

- The LAPACK call site is:
  - `spline.f90:39`: `call dptsv(n-2, 1, d, dl, c, n-2, info)`

- Even if `--implicit-interface` is used and we link against system LAPACK/BLAS (`-llapack -lblas`), we currently fail at link time with `undefined reference to dptsv`.

- Concrete ABI evidence on a typical system LAPACK:
  ```
  $ nm -D /usr/lib/liblapack.so | rg '\bdptsv_\b'
  0000000000272780 T dptsv_

  $ lfortran -c spline.f90 --implicit-interface -o spline_module.o
  $ nm -u spline_module.o | rg '\bdptsv'
                   U dptsv
  ```
  so LFortran emits a reference to `dptsv` (no underscore) while system LAPACK exports `dptsv_`.

- #9067 discusses `--mangle-underscore` and notes it appends underscores in `unique_symbols.cpp`, but in this case `--mangle-underscore` does not change the external reference for `dptsv`.

This makes `spline` a small, focused reproducer for external-library name mangling compatibility with system BLAS/LAPACK.

**Comment by krystophny** [comment]
Update:

- Draft PR #9450 fixes the `dptsv`/`dptsv_` mismatch for implicit interfaces under `--mangle-underscore` (and stops representing implicit externals as `BindC`).

Evidence (local):
- With #9444 + #9450, `itpplasma/spline` builds/links against system LAPACK/BLAS and `spline_test.f90` runs (output: `Hello Splines`).
