### PR TITLE
ci: resolve failures

### PR DESCRIPTION
**Pull request by kmr-srbh**
We have a hard dependency on `libunwind` for LLVM > 11.

### CODE REVIEW

**Comment by kmr-srbh** [comment]
We have a circular dependency now. The CI failure in this PR will get resolved by #5984, and the CI failure in that PR will get resolved by this PR.

**Comment by kmr-srbh** [comment]
The LLVM 16 failure is:

```console
Errors while running CTest
	1041 - template_sort_01_FAST (SEGFAULT)
	1042 - template_sort_02_FAST (SEGFAULT)
```

Release build failure is:
```console
[86/120] Building CXX object src/libasr/CMakeFiles/asr.dir/codegen/asr_to_llvm.cpp.o
FAILED: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_llvm.cpp.o 
sccache /usr/bin/c++ -DHAVE_TARGET_X86=1 -DHAVE_WHEREAMI=1 -DHAVE_ZLIB=1 -DLCOMPILERS_FAST_ALLOC=1 -I/home/runner/work/lfortran/lfortran/src/libasr/.. -isystem /home/runner/micromamba/envs/lf/include -Werror -Wall -Wextra -O3 -funroll-loops -DNDEBUG -std=gnu++17 -fPIC -fno-rtti -Wno-deprecated-declarations -MD -MT src/libasr/CMakeFiles/asr.dir/codegen/asr_to_llvm.cpp.o -MF src/libasr/CMakeFiles/asr.dir/codegen/asr_to_llvm.cpp.o.d -o src/libasr/CMakeFiles/asr.dir/codegen/asr_to_llvm.cpp.o -c /home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp
/home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp: In member function ‘void LCompilers::ASRToLLVMVisitor::compute_fmt_specifier_and_arg(std::vector<std::__cxx11::basic_string<char> >&, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, LCompilers::ASR::expr_t*, const LCompilers::Location&, bool)’:
/home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp:8479:31: error: ‘d’ may be used uninitialized [-Werror=maybe-uninitialized]
 8479 |                 args.push_back(d);
      |                 ~~~~~~~~~~~~~~^~~
In file included from /usr/include/c++/13/vector:66,
                 from /usr/include/c++/13/functional:64,
                 from /home/runner/micromamba/envs/lf/include/llvm/ADT/STLExtras.h:29,
                 from /home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp:6:
/usr/include/c++/13/bits/stl_vector.h:1281:7: note: by argument 2 of type ‘llvm::Value* const&’ to ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = llvm::Value*; _Alloc = std::allocator<llvm::Value*>]’ declared here
 1281 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp:8439:26: note: ‘d’ declared here
 8439 |             llvm::Value *d;
      |                          ^
/home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp:8479:31: error: ‘d’ may be used uninitialized [-Werror=maybe-uninitialized]
 8479 |                 args.push_back(d);
      |                 ~~~~~~~~~~~~~~^~~
/usr/include/c++/13/bits/stl_vector.h:1281:7: note: by argument 2 of type ‘llvm::Value* const&’ to ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = llvm::Value*; _Alloc = std::allocator<llvm::Value*>]’ declared here
 1281 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/home/runner/work/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp:8439:26: note: ‘d’ declared here
 8439 |             llvm::Value *d;
      |                          ^
cc1plus: all warnings being treated as errors
[87/120] Building CXX object src/libasr/CMakeFiles/asr.dir/pickle.cpp.o
[88/120] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/semantics/ast_to_asr.cpp.o
[89/120] Building CXX object src/lfortran/tests/CMakeFiles/test_stacktrace.dir/test_stacktrace.cpp.o
[90/120] Building CXX object src/lfortran/tests/CMakeFiles/test_lfortran.dir/test_parse.cpp.o
[91/120] Building CXX object src/lfortran/tests/CMakeFiles/test_lfortran.dir/test_ast.cpp.o
[92/120] Building CXX object src/lfortran/tests/CMakeFiles/test_lfortran.dir/test_stacktrace2.cpp.o
[93/120] Building CXX object src/lfortran/tests/CMakeFiles/test_lfortran.dir/test_asm.cpp.o
[94/120] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/ast_to_openmp.cpp.o
FAILED: src/lfortran/CMakeFiles/lfortran_lib.dir/ast_to_openmp.cpp.o 
sccache /usr/bin/c++ -DHAVE_TARGET_X86=1 -DHAVE_WHEREAMI=1 -DHAVE_ZLIB=1 -DLCOMPILERS_FAST_ALLOC=1 -I/home/runner/work/lfortran/lfortran/src -I/home/runner/work/lfortran/lfortran/src/lfortran -I/home/runner/work/lfortran/lfortran/src/libasr/.. -isystem /home/runner/micromamba/envs/lf/include -Werror -Wall -Wextra -O3 -funroll-loops -DNDEBUG -std=gnu++17 -fPIC -fno-rtti -MD -MT src/lfortran/CMakeFiles/lfortran_lib.dir/ast_to_openmp.cpp.o -MF src/lfortran/CMakeFiles/lfortran_lib.dir/ast_to_openmp.cpp.o.d -o src/lfortran/CMakeFiles/lfortran_lib.dir/ast_to_openmp.cpp.o -c /home/runner/work/lfortran/lfortran/src/lfortran/ast_to_openmp.cpp
/home/runner/work/lfortran/lfortran/src/lfortran/ast_to_openmp.cpp: In member function ‘void LCompilers::LFortran::AST::ASTToOPENMPVisitor::visit_AttrType(const LCompilers::LFortran::AST::AttrType_t&)’:
/home/runner/work/lfortran/lfortran/src/lfortran/ast_to_openmp.cpp:336:22: error: ‘k[0].LCompilers::LFortran::AST::kind_item_t::m_id’ may be used uninitialized [-Werror=maybe-uninitialized]
  336 |                 k[0].m_id == nullptr) {
      |                 ~~~~~^~~~
/home/runner/work/lfortran/lfortran/src/lfortran/ast_to_openmp.cpp:308:25: note: ‘k’ declared here
  308 |             kind_item_t k[2];
      |                         ^
cc1plus: all warnings being treated as errors
[95/120] Building CXX object src/lfortran/tests/CMakeFiles/test_lfortran.dir/test_serialization.cpp.o
```

GFortran failure is fixed in #5984.

Why did the above errors did not come up before?

**Comment by assem2002** [comment]
I don't know what made all this mess. but maybe github CI updated CMake which in turn started to use new versions of the packages we use.

**Comment by assem2002** [comment]
for the circular dependecy, can't we add all these fixes https://github.com/lfortran/lfortran/pull/5984, https://github.com/lfortran/lfortran/pull/5984 in one PR (this PR) to get our CI working and unblock us?

**Comment by kmr-srbh** [comment]
Attempting the fix in a single PR.

**Comment by gxyd** [comment]
Is this ready to be reviewed?

**Comment by kmr-srbh** [comment]
> I am guessing the compiler version was updated?

Yes. It was updated from 11.4.0 to 13.3.0

**Comment by gxyd** [comment]
Maybe fix the C compiler version for now, to let the "Release build" CI job to pass, as it current blocks merging the other PR's, and we slowly fix the issues with GCC 13.3.0?

File: .github/workflows/CI.yml [hunk 1]
```diff
@@ -1422,8 +1433,9 @@ jobs:
         shell: bash -e -l {0}
         run: |
             ./build0.sh
-            export CXXFLAGS="-Werror"
-            export CFLAGS="-Werror"
+            # FIXME: Using the below flag generates many warnings.
+            # export CXXFLAGS="-Werror"
+            # export CFLAGS="-Werror"
```
Comment (gxyd) [inline .github/workflows/CI.yml:1438]: will something like: `export CC=gcc-11` and `export CXX=g++-11` work here to fix the C compiler version?

File: .github/workflows/CI.yml [hunk 2]
```diff
@@ -1548,6 +1560,7 @@ jobs:
             mlir=19.1.6
             llvm=19.1.6
             llvm-openmp=19.1.6
+            libunwind
```
Comment (gxyd) [inline .github/workflows/CI.yml:1563]: Ideally fixing the `libunwind` would be the best.

Comment (kmr-srbh) [reply .github/workflows/CI.yml:1563]: Yes!

File: .github/workflows/CI.yml (hunk 1 above)
Comment (kmr-srbh) [reply .github/workflows/CI.yml:1440]: Done in [2a8acdc](https://github.com/lfortran/lfortran/pull/5983/commits/2a8acdcaa81074238cde40e00129a0b711dce5df).

Comment (kmr-srbh) [reply .github/workflows/CI.yml:1440]: It does not find it automatically. I think we will need to install it.

**Comment by kmr-srbh** [comment]
The CI should hopefully pass now.

File: .github/workflows/CI.yml (hunk 1 above)
Comment (gxyd) [reply .github/workflows/CI.yml:1440]: Not sure, why don't see that commit anymore

Comment (kmr-srbh) [reply .github/workflows/CI.yml:1440]: The changes in that commit had failed. [ec0bc56](https://github.com/lfortran/lfortran/pull/5983/commits/ec0bc566ee45f18a33086064ff9b5cba59ee3192) is the new commit.

**Comment by kmr-srbh** [comment]
The current failure is:

```console
 /usr/bin/ld: cannot find /lib64/libc.so.6: No such file or directory
/usr/bin/ld: cannot find /usr/lib64/libc_nonshared.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o modules_15 CMakeFiles/modules_15.dir/modules_15.f90.o CMakeFiles/modules_15.dir/modules_15b.f90.o CMakeFiles/modules_15.dir/modules_15c.c.o  -L/home/runner/micromamba/envs/lf/lib -L/home/runner/micromamba/envs/lf/lib -L/home/runner/micromamba/envs/lf/lib/gcc/x86_64-conda-linux-gnu/11.4.0 -L/home/runner/micromamba/envs/lf/lib/gcc -L/home/runner/micromamba/envs/lf/x86_64-conda-linux-gnu/lib -L/home/runner/micromamba/envs/lf/x86_64-conda-linux-gnu/sysroot/lib -L/home/runner/micromamba/envs/lf/x86_64-conda-linux-gnu/sysroot/usr/lib -lgcc -lgcc_s -lc -lgcc -lgcc_s  -L"/home/runner/work/lfortran/lfortran/src/bin/../runtime" -Wl,-rpath,"/home/runner/work/lfortran/lfortran/src/bin/../runtime" -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/runner/micromamba/envs/lf/lib -Wl,-rpath-link,/home/runner/micromamba/envs/lf/lib -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
make[2]: *** [CMakeFiles/modules_15.dir/build.make:127: modules_15] Error 10
make[1]: *** [CMakeFiles/Makefile2:20759: CMakeFiles/modules_15.dir/all] Error 2
```

When I faced this issue locally before, it was an issue with my `conda` environment. Deleting the environment and creating a new one had fixed it, but why does it happen at the CI and how do we fix it?

File: .github/workflows/CI.yml (hunk 2 above)
Comment (gxyd) [reply .github/workflows/CI.yml:1565]: Fix whatever the current version we install and passes the tests for now. (this isn't a priority first though, current failing test would be a higher priority ofcourse)

**Comment by gxyd** [comment]
I pushed a commit, just to print the values of `LFORTRAN_LINKER` environment variable.

File: .github/workflows/CI.yml [hunk 3]
```diff
@@ -390,6 +392,9 @@ jobs:
           environment-file: ci/environment_linux.yml
           create-args: >-
             python=3.10
+            gcc=11
```
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply .github/workflows/CI.yml]: Yes, it may be conflicting with the version present on the workflow runner.

**Comment by kmr-srbh** [comment]
The job `Check Release build`passed! Thanks a lot for helping with this @gxyd! This would have been really difficult to fix without your support. :)

File: .github/workflows/CI.yml (hunk 2 above)
Comment (gxyd) [reply .github/workflows/CI.yml:1572]: I think we can fix this to version 1.7.2, as I see that here in [a passing CI job](https://productionresultssa14.blob.core.windows.net/actions-results/e9006604-6fcd-4427-8688-d7a07d09a129/workflow-job-run-77243af2-8349-533d-2f41-71febbe7ba72/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-01-13T12%3A22%3A16Z&sig=UTVG2yNWJOKLhIYgVJ5Tq6GoSJEK71iQhj97HbCIBgk%3D&ske=2025-01-13T21%3A48%3A55Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-01-13T09%3A48%3A55Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2025-01-13T12%3A12%3A11Z&sv=2024-11-04) version 1.7.2 was used when we didn't specify the version of `libunwind`.

Comment (kmr-srbh) [reply .github/workflows/CI.yml]: Done in [8a80703](https://github.com/lfortran/lfortran/pull/5983/commits/8a8070354c48feb44dbb9de77ff648e6b9614bb9).

**Comment by gxyd** [comment]
We can maybe undo the last commit, first to make sure that we unblock merging of the other PR's, what do you think @kmr-srbh ?

Once that happens we can may changes one by one.

**Comment by gxyd** [comment]
Ah, I see, seems like the current failure on this PR isn't related to our changes at all actually, see: https://github.com/lfortran/lfortran/issues/5724

We encountered the flaky test failure.

File: .github/workflows/CI.yml [hunk 4]
```diff
@@ -396,12 +398,22 @@ jobs:
...
           key: ${{ github.job }}-${{ matrix.os }}
 
+      - name: Install GCC and G++ version 11
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y gcc-11 g++-11
+          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
+          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
+          gcc --version
+          g++ --version
```
[the remark this answers is not in the document]
Comment (gxyd) [reply .github/workflows/CI.yml]: Now the question is, since CI by default uses GCC version 13.3.0, which version should be preferred for devs now version 11.4.0 or 13.3.0?

We would need a separate issue to resolve the failing tests with version 13.3.0 of GCC, (some) of the failing tests with GCC version 13.3.0 can be seen here: https://github.com/lfortran/lfortran/actions/runs/12742005151/job/35513044996 (one of the CI run from this PR)

[the remark this answers is not in the document]
Comment (gxyd) [reply .github/workflows/CI.yml]: I just read this page here: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md, seems like the versions for GNU C++ supported with ubuntu 24.04 image on github CI runner are:
```console
GNU C++: 12.3.0, 13.3.0, 14.2.0
```

[the remark this answers is not in the document]
Comment (gxyd) [reply .github/workflows/CI.yml]: @certik your help on this comment especially would be helpful.

**Comment by gxyd** [comment]
There are some open conversations in this PR, which would need to be discussed/addressed. I've merged this PR to unblock merging other PR's.

File: .github/workflows/CI.yml (hunk 4 above)
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply .github/workflows/CI.yml]: > which version should be preferred for devs now version 11.4.0 or 13.3.0

I have been using GCC 14.2.0 for very long and never encountered this issue. I think the issue occurs with Release build only.

[the remark this answers is not in the document]
Comment (gxyd) [reply .github/workflows/CI.yml]: > I have been using GCC 14.2.0 for very long and never encountered this issue. I think the issue occurs with Release build only.

I think that's true, since the other CI jobs use GCC version 13.3.0

File: integration_tests/format_04.f90 [hunk 5]
```diff
@@ -27,8 +27,8 @@ program format_04
 print "(12(i3))", 1,2,3,4,5,6,7,8,9,10,11,12
 print "(4(i3),' hello')", 1,2,3,4,5,6,7,8,9,10,11,12,13,14
 print '(i0)', f, -f
-print '(d0.0,1x,d0.1,1x,d0.2)',a,b,c
-print '(d0.0,1x,d0.1,1x,d0.2)',-a,-b,-c
+print '(d12.5,1x,d0.1,1x,d0.2)',a,b,c
+print '(d12.5,1x,d0.1,1x,d0.2)',-a,-b,-c
```
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply integration_tests/format_04.f90:31]: Opened #5994 for this.

[the remark this answers is not in the document]
Comment (gxyd) [reply integration_tests/format_04.f90:31]: Perfect, thanks for opening the issue for it.

**Comment by kmr-srbh** [comment]
Opening issues for them. :+1:

File: integration_tests/CMakeLists.txt [hunk 6]
```diff
@@ -1566,8 +1566,8 @@ RUN(NAME template_simple_01 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
 RUN(NAME template_simple_02 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
 RUN(NAME template_simple_03 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
 RUN(NAME template_simple_04 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
-RUN(NAME template_sort_01 LABELS llvm llvm_wasm llvm_wasm_emcc)
-RUN(NAME template_sort_02 LABELS llvm llvm_wasm llvm_wasm_emcc)
+RUN(NAME template_sort_01 LABELS llvm llvm_wasm llvm_wasm_emcc NOFAST)      # FIXME: This test had worked before, but fails now with --fast.
+RUN(NAME template_sort_02 LABELS llvm llvm_wasm llvm_wasm_emcc NOFAST)      # FIXME: This test had worked before, but fails now with --fast.
```
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply integration_tests/CMakeLists.txt:1570]: Done.

File: .github/workflows/CI.yml [hunk 7]
```diff
@@ -71,8 +71,9 @@ jobs:
         shell: bash -e -l {0}
         if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
         run: |
-            export CXXFLAGS="-Werror"
-            export CFLAGS="-Werror"
+            # FIXME: Using the below flag generates many warnings.
+            # export CXXFLAGS="-Werror"
+            # export CFLAGS="-Werror"
```
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply .github/workflows/CI.yml:76]: Done.

File: .github/workflows/CI.yml [hunk 8]
```diff
@@ -396,12 +398,20 @@ jobs:
           variant: sccache
           key: ${{ github.job }}-${{ matrix.os }}
 
+      - name: Install GCC and G++ version 11
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y gcc-11 g++-11
+          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
+          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
```
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply .github/workflows/CI.yml:406]: Done.
