### ISSUE TITLE
Host dummy procedure used from a contained procedure is resolved as a global procedure (undefined symbol / codegen error)

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#12823]
A contained (internal) procedure that uses its host's dummy procedure `f` is compiled as if `f` were a global procedure named `f`. If the internal procedure calls `f`, the link fails with an undefined symbol `_f`. If it passes `f` on to another procedure, code generation fails. With an explicit `interface` for `f` instead of `external`, code generation also fails.

## Reproducer

`host1.f90`:

```fortran
program main
external add_one
real(8) :: y
y = 0
call w(add_one, y)
if (abs(y - 1) > 1d-12) error stop
print *, 'ok'
end program

subroutine w(f, y)
external f
real(8) :: y
call inner()
contains
subroutine inner()
call f(y)
end subroutine
end subroutine

subroutine add_one(x)
real(8) :: x
x = x + 1
end subroutine
```

```
lfortran --implicit-interface host1.f90
```

`host2.f90` passes the host dummy on instead of calling it (`lib.f90` is compiled separately):

```fortran
subroutine w(f, y)
external f
real(8) :: y
call inner()
contains
subroutine inner()
call lib(f, y)
end subroutine
end subroutine
```

```fortran
subroutine lib(p, y)
external p
real(8) :: y
call p(y)
end subroutine
```

```
lfortran -c --implicit-interface lib.f90 -o lib.o
lfortran -c --implicit-interface host2.f90 -o host2.o
```

`host3.f90` is `host1.f90` with explicit interfaces:

```fortran
program main
interface
subroutine add_one(x)
real(8) :: x
end subroutine
end interface
real(8) :: y
y = 0
call w(add_one, y)
if (abs(y - 1) > 1d-12) error stop
print *, 'ok'
end program

subroutine w(f, y)
interface
subroutine f(x)
real(8) :: x
end subroutine
end interface
real(8) :: y
call inner()
contains
subroutine inner()
call f(y)
end subroutine
end subroutine

subroutine add_one(x)
real(8) :: x
x = x + 1
end subroutine
```

```
lfortran host3.f90
```

## Actual

`host1.f90`:

```
Undefined symbols for architecture arm64:
  "_f", referenced from:
      _w.inner in host1.tmp_<random>.o
ld: symbol(s) not found for architecture arm64
```

`host2.f90`:

```
code generation error: Can't resolve var to Function 'f'
```

`host3.f90`:

```
code generation error: Subroutine code not generated for 'f'
```

## Expected

All three compile, and `host1.f90` and `host3.f90` print `ok`, as with gfortran (`gfortran host1.f90 && ./a.out` prints ` ok`, and the same for `host3.f90`; `gfortran -c host2.f90` compiles, and linked with `lib.o` and a main program it prints ` ok`).

Found while working on #12817 (#12815). Tested with LFortran at 5143784bff (main) and ae5a9d1aca (PR #12817 branch); both fail the same way.
