### PR TITLE
Port intrinsics to use IntrinsicFunction

### PR DESCRIPTION
**Pull request by certik**
TODO:
* [x] implement an ASR pass that transforms all IntrinsicFunctions into (generic) calls into another expression
* [x] transform arguments recursively
* [x] instead of importing it from the frontend language, let's implement it in ASR itself. This is an intermediate step, but it might also end up being the final design (we'll see), since it decouples the implementation from the front end languages completely and easily allows us to "specialize" for all types (such as any rank array), which otherwise can get quite complex in the frontend language (requires generics, etc.)
* [x] let's finish loggamma to just return the argument
* [x] Return actual C implementation (can be changed later) using BindC
* [x] add compile time evaluation in ASR->ASR pass
* [x] the compile time evaluation must be done already in IntrinsicFunction so that the frontend has access to it
* [x] uncomment lines in `integration_tests/intrinsics_19.f90`
* [x] print (in `--show-asr`) the actual intrinsic ID as a string
* [x] Use the "wrapper" approach to call C, not directly
* [x] add a test for both compile and runtime results of log_gamma; our current tests do not check the answer, so we do not know that it is correct; In this test, also test nested calls like `log_gamma(log_gamma(x) + 3*log_gamma(x+log_gamma(x)))`, to ensure everything gets substituted correctly recursively

Subsequent PRs:

* [ ] add another function, make the API to hook a new function simpler
* [ ] cache the generated functions based on type
* [ ] figure out a solution for separate compilation (minpack), where we should link the functions only once
* [ ] then let's figure out how to get it working for arrays
* [ ] let's use it for "sum" or "minloc", that might be quite simple to get working
* [ ] make the code of `instantiate_LogGamma` simpler by creating some nice API to create ASR

### CODE REVIEW

**Comment by certik** [comment]
TODO:
* [ ] implement an ASR pass that transforms all IntrinsicFunctions into (generic) calls into the runtime library from the surface language
* [ ] add compile time evaluation
* [ ] print (in `--show-asr`) the actual intrinsic ID as a string

File: src/libasr/pass/intrinsic_function.cpp [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+                for (size_t i=0; i < x.n_args; i++) {
+                    // TODO: handle the case if the argument changes
+                    visit_expr(*x.m_args[i]);
+                }
+                // TODO: here we must get access to the pure ASR implementation
+                // of LogGamma, as provided by the frontend, let's say
+                // it is assigned to this "fc":
+                // ASR::FunctionCall_t *fc = ...;
+                // TODO: Return "fc" instead of "self" here
+                throw LCompilersException("TODO: change IntrinsicFunction to FunctionCall");
```
Comment (certik) [inline src/libasr/pass/intrinsic_function.cpp:52]: @czgdp1807 do you know how to use a pass to change an expression to another expression? I see examples how to do it with a statement, as well as how to changes details of an expression (but keep the node), but here I need to replace the `IntrinsicFunction` node with a `FunctionCall` node. Do you know how to do it?

A separate issue is how to actually get access to the LogGamma implementation from the frontend, but I'll handle that later. First I'll just return `RealConstant(1.0)` or something like that, just to see that it works.

Comment (czgdp1807) [reply src/libasr/pass/intrinsic_function.cpp:52]: > here I need to replace the `IntrinsicFunction` node with a `FunctionCall` node

You can use the following pattern where I replace `FunctionCall` with a different `FunctionCall`. I guess your use case is to replace `IntrinsicFunction` with a `FunctionCall`. So changes you would need to make are as follows,

1. Instead of implementing `void replace_FunctionCall(ASR::FunctionCall_t* x)` in `ReplaceFunctionCalls`, you will be required to implement `void replace_IntrinsicFunction(ASR::IntrinsicFunction_t* x)` in `ReplaceIntrinsicFunction` (a new class you will create with a similar pattern as `ReplaceFunctionCalls`).
2. In `*current_expr = new_call;` statement, `new_call` will be the new `FunctionCall` which you will be replacing `IntrinsicFunction` node with.
3. You can rename the visitor, `ReplaceFunctionCallsVisitor` with `ReplaceIntrinsicFunctionVisitor` (which will call the replacer, `ReplaceIntrinsicFunction`). However no implementation change should be required in the visitor.

https://github.com/lfortran/lfortran/blob/9b5fe9c31ce525aa567db0da924b312955a9c66e/src/libasr/pass/pass_array_by_data.cpp#L303-L373

Comment (certik) [reply src/libasr/pass/intrinsic_function.cpp:52]: Awesome, thanks! I'll try it.

File: src/libasr/pass/intrinsic_function.cpp [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+    void replace_IntrinsicFunction(ASR::IntrinsicFunction_t* x) {
+        switch (x->m_intrinsic_id) {
+            case (static_cast<int64_t>(ASRUtils::IntrinsicFunctions::LogGamma)) : {
+                LFORTRAN_ASSERT(x->n_args == 1)
+                // Replace any IntrinsicFunctions in the argument first:
+                current_expr_copy = current_expr;
+                current_expr = &(x->m_args[0]);
+                replace_expr(x->m_args[0]);
+                ASR::expr_t *arg = *current_expr; // Use the converted arg
+                current_expr = current_expr_copy;
```
Comment (certik) [inline src/libasr/pass/intrinsic_function.cpp:48]: @czgdp1807 any idea why this part does not properly replace the argument? I can't see the issue right now, but I think the logic must be incorrect. The PR, as is, works:
```console
$ lfortran examples/expr2.f90 
2.50000000e+01
```
But you can trigger this issue with this patch:
```diff
--- a/examples/expr2.f90
+++ b/examples/expr2.f90
@@ -4,6 +4,6 @@ implicit none
 real :: x
 
 x = (2+3)*5
-print *, log_gamma(x)
+print *, log_gamma(log_gamma(x))
 
 end program
```
Then it gives:
```console
$ lfortran --show-llvm examples/expr2.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1831
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 768
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 273
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 295
    diagnostics, lm.files.back().in_filename);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 328
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6521
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4171
  File "../libasr/asr.h", line 4148
  File "../libasr/asr.h", line 4172
  File "../libasr/asr.h", line 3924
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1269
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4174
  File "../libasr/asr.h", line 3933
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2307
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4189
  File "../libasr/asr.h", line 3969
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5558
    handle_print(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5608
    this->visit_expr_wrapper(x.m_values[i], true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4136
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4232
  File "../libasr/asr.h", line 4006
  File "../libasr/asr.h", line 4237
LCompilersException: visit_IntrinsicFunction() not implemented
```

File: src/libasr/pass/intrinsic_function.cpp (hunk 1 above)
Comment (certik) [reply src/libasr/pass/intrinsic_function.cpp]: This worked, thank you! This particular issue is resolved with subsequent commits.

File: src/libasr/pass/intrinsic_function.cpp (hunk 2 above)
Comment (czgdp1807) [reply src/libasr/pass/intrinsic_function.cpp:48]: I will look into it.

Comment (czgdp1807) [reply src/libasr/pass/intrinsic_function.cpp]: Merge #1054 into main and then rebase your PR on top of main.

**Comment by certik** [comment]
Thanks for the fix! I merged #1054 into master and rebased.

**Comment by certik** [comment]
I tested it by hand, I think it works, thanks @czgdp1807 !

File: src/libasr/ASR.asdl [hunk 3]
```diff
@@ -223,6 +223,8 @@ expr
     | NamedExpr(expr target, expr value, ttype type)
     | FunctionCall(symbol name, symbol? original_name, call_arg* args,
             ttype type, expr? value, expr? dt)
+    | IntrinsicFunction(expr* args, int intrinsic_id, int overload_id,
+            ttype type, expr? value)
```
Comment (certik) [inline src/libasr/ASR.asdl:227]: This might make it a little more clear:
```suggestion
    | IntrinsicFunctionCall(expr* args, int intrinsic_id, int overload_id,
            ttype type, expr? value)
```

Comment (certik) [reply src/libasr/ASR.asdl:227]: Another application of this: https://github.com/lcompilers/lpython/pull/1342/files#diff-5d1686bbf82a8cae17e6ad618b17bd948349c70efde2f55c2caecc651e27c9d7R229, the IntrinsicFunctionCall could be used to represent `_lcompilers_tuple_compare`. This function accepts any type, so one of the `overload_id` would mean "template", and the type would then be inferred from `args`. In this case the restriction would be that both `a` and `b` arguments in `args` must have exactly the same type.

**Comment by certik** [comment]
TODO:
* [ ] instead of importing it from the frontend language, let's implement it in ASR itself. This is an intermediate step, but it might also end up being the final design (we'll see), since it decouples the implementation from the front end languages completely and easily allows us to "specialize" for all types (such as any rank array), which otherwise can get quite complex in the frontend language (requires generics, etc.)
* [ ] let's finish loggamma to just return the argument
* [ ] then let's figure out how to get it working for arrays
* [ ] let's use it for "sum" or "minloc", that might be quite simple to get working

File: src/libasr/pass/intrinsic_function.cpp [hunk 4]
```diff
@@ -33,6 +33,20 @@ class ReplaceIntrinsicFunction: public ASR::BaseExprReplacer<ReplaceIntrinsicFun
...
     {}
 
+    ASR::symbol_t* instantiate_LogGamma(ASR::ttype_t *arg_type) {
+        ASR::asr_t* new_subrout = nullptr; /*ASRUtils::make_Function_t_util(al, x->base.base.loc,
+                                new_symtab, s2c(al, new_name), x->m_dependencies, x->n_dependencies,
+                                new_args.p, new_args.size(),  new_body.p, new_body.size(),
+                                return_var, x_func_type->m_abi, x->m_access, x_func_type->m_deftype,
+                                s2c(al, new_bindc_name), x_func_type->m_elemental,
+                                x_func_type->m_pure, x_func_type->m_module, x_func_type->m_inline,
+                                x_func_type->m_static, nullptr, 0, nullptr, 0, false, false, false); */
```
Comment (certik) [inline src/libasr/pass/intrinsic_function.cpp:43]: Here we have to now create the Function, and register it in the symbol table somewhere, such as in global scope.

**Comment by Thirumalai-Shaktivel** [comment]
@certik Am I doing this right?

File: src/libasr/pass/intrinsic_function.cpp [hunk 5]
```diff
@@ -58,17 +83,18 @@ class ReplaceIntrinsicFunction: public ASR::BaseExprReplacer<ReplaceIntrinsicFun
                 replace_expr(x->m_args[0]);
                 ASR::expr_t *arg = *current_expr; // Use the converted arg
                 current_expr = current_expr_copy_;
-                ASR::symbol_t* new_func_sym = instantiate_LogGamma(ASRUtils::expr_type(x->m_args[0]));
-
+                std::string new_name = "logGamma";
```
Comment (certik) [inline src/libasr/pass/intrinsic_function.cpp:86]: Here we need to call the function that returns a unique name, something like `_lcompilers_LogGamma_13`.

**Comment by certik** [comment]
@Thirumalai-Shaktivel yes, perfect! Thank you, great progress.

**Comment by certik** [comment]
Here is how to test the new pass:
```console
$ lfortran --pass intrinsic_function examples/expr2.f90
ASR verify pass error: ASR verify: FunctionCall::m_name `logGamma` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1942
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 865
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 342
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7074
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 217
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 110
    throw LCompilersException("Verify failed");
LCompilersException: Verify failed
```

**Comment by certik** [comment]
PR #1355 shows where the error is:
```
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/intrinsic_function.cpp", line 87
    ASR::symbol_t* new_func_sym = instantiate_LogGamma(al, global_scope,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/intrinsic_function.cpp", line 58
    global_scope->add_symbol(new_name, new_symbol);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_scopes.h", line 74
    LCOMPILERS_ASSERT(scope.find(name) == scope.end())
AssertFailed: scope.find(name) == scope.end()
```
We need to define a unique symbol.

File: src/libasr/pass/intrinsic_function.cpp (hunk 5 above)
Comment (certik) [reply src/libasr/pass/intrinsic_function.cpp]: Fixed in fe1007254f613b39f24d849ec37dfd1eb6fe730c.

**Comment by certik** [comment]
This now works:
```console
$ lfortran --show-asr --pass intrinsic_function examples/expr2.f90 
(TranslationUnit (SymbolTable 1 {_lcompilers_LogGamma: (Function (SymbolTable 3 {_lcompilers_LogGamma: (Variable 3 _lcompilers_LogGamma [] ReturnVar () () Default (Real 4 []) Source Public Required .false.), x: (Variable 3 x [] In () () Default (Real 4 []) Source Public Required .false.)}) _lcompilers_LogGamma (FunctionType [(Real 4 [])] (Real 4 []) Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [(Var 3 x)] [(= (Var 3 _lcompilers_LogGamma) (Var 3 x) ())] (Var 3 _lcompilers_LogGamma) Public .false. .false.), _lcompilers_LogGamma1: (Function (SymbolTable 4 {_lcompilers_LogGamma1: (Variable 4 _lcompilers_LogGamma1 [] ReturnVar () () Default (Real 4 []) Source Public Required .false.), x: (Variable 4 x [] In () () Default (Real 4 []) Source Public Required .false.)}) _lcompilers_LogGamma1 (FunctionType [(Real 4 [])] (Real 4 []) Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [(Var 4 x)] [(= (Var 4 _lcompilers_LogGamma1) (Var 4 x) ())] (Var 4 _lcompilers_LogGamma1) Public .false. .false.), _lcompilers_LogGamma2: (Function (SymbolTable 5 {_lcompilers_LogGamma2: (Variable 5 _lcompilers_LogGamma2 [] ReturnVar () () Default (Real 4 []) Source Public Required .false.), x: (Variable 5 x [] In () () Default (Real 4 []) Source Public Required .false.)}) _lcompilers_LogGamma2 (FunctionType [(Real 4 [])] (Real 4 []) Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [(Var 5 x)] [(= (Var 5 _lcompilers_LogGamma2) (Var 5 x) ())] (Var 5 _lcompilers_LogGamma2) Public .false. .false.), _lcompilers_LogGamma3: (Function (SymbolTable 6 {_lcompilers_LogGamma3: (Variable 6 _lcompilers_LogGamma3 [] ReturnVar () () Default (Real 4 []) Source Public Required .false.), x: (Variable 6 x [] In () () Default (Real 4 []) Source Public Required .false.)}) _lcompilers_LogGamma3 (FunctionType [(Real 4 [])] (Real 4 []) Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [(Var 6 x)] [(= (Var 6 _lcompilers_LogGamma3) (Var 6 x) ())] (Var 6 _lcompilers_LogGamma3) Public .false. .false.), expr2: (Program (SymbolTable 2 {x: (Variable 2 x [] Local () () Default (Real 4 []) Source Public Required .false.)}) expr2 [] [(= (Var 2 x) (Cast (IntegerBinOp (IntegerBinOp (IntegerConstant 2 (Integer 4 [])) Add (IntegerConstant 3 (Integer 4 [])) (Integer 4 []) (IntegerConstant 5 (Integer 4 []))) Mul (IntegerConstant 5 (Integer 4 [])) (Integer 4 []) (IntegerConstant 25 (Integer 4 []))) IntegerToReal (Real 4 []) (RealConstant 25.000000 (Real 4 []))) ()) (Print () [(FunctionCall 1 _lcompilers_LogGamma2 1 _lcompilers_LogGamma2 [((RealBinOp (FunctionCall 1 _lcompilers_LogGamma 1 _lcompilers_LogGamma [((Var 2 x))] (Real 4 []) () ()) Add (FunctionCall 1 _lcompilers_LogGamma1 1 _lcompilers_LogGamma1 [((RealBinOp (Var 2 x) Add (Cast (IntegerConstant 1 (Integer 4 [])) IntegerToReal (Real 4 []) (RealConstant 1.000000 (Real 4 []))) (Real 4 []) ()))] (Real 4 []) () ()) (Real 4 []) ()))] (Real 4 []) () ()) (FunctionCall 1 _lcompilers_LogGamma3 1 _lcompilers_LogGamma3 [((Var 2 x))] (Real 4 []) () ())] () ())])}) [])
```

**Comment by certik** [comment]
@Thirumalai-Shaktivel I made further progress and updated the TODO list at the very top. Just the three missing items have to be done.

**Comment by Thirumalai-Shaktivel** [comment]
Got it. Now, I will continue to work on the TODO list.

**Comment by certik** [comment]
Awesome, thanks!

**Comment by Thirumalai-Shaktivel** [comment]
Here is the output and LLVM IR:
```fortran
real :: x
x = (2+3)*5
print *, log_gamma(x)
```
```console
$ lfortran examples/expr2.f90
5.47847290e+01
$ lfortran examples/expr2.f90 --show-llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [9 x i8] c"%13.8e%s\00", align 1

declare float @_lfortran_slog_gamma(float)

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %x = alloca float, align 4
  store float 2.500000e+01, float* %x, align 4
  %2 = load float, float* %x, align 4
  %3 = call float @_lfortran_slog_gamma(float %2)
  %4 = fpext float %3 to double
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @2, i32 0, i32 0), double %4, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare void @_lfortran_printf(i8*, ...)
```

**Comment by Thirumalai-Shaktivel** [comment]
We completed the TODO list in this PR. @certik you can have the final review on this PR.

**Comment by Thirumalai-Shaktivel** [comment]
I didn't get this?
> figure out a solution for separate compilation (minpack), where we should link the functions only once

**Comment by certik** [comment]
@Thirumalai-Shaktivel great job! Thank you.

Do you mind calling the C function inside our generated wrapper?

I know it is redundant in this particular case, but I want this PR to be like a "template" how to implement any function and in general we should generate a new ASR function, and inside implement it (whether directly in ASR or calling into C). Our optimizer (or LLVM) will inline it anyway, so there is no performance overhead, but it makes things "canonical", and we can then easily extend this approach for all intrinsics.

**Comment by certik** [comment]
> I didn't get this?
> 
> > figure out a solution for separate compilation (minpack), where we should link the functions only once

So your current implementation might actually work, since you are calling the C function directly. But the "wrapper" implementation (see my previous comment) will not work, because it will generate the wrapper for each file that is compiled separately, and consequently it will fail at link time with duplicate symbols. We will need to figure out solutions to this. Minpack doesn't use log_gamma, so we are fine for now, but once we implement an intrinsic that Minpack uses, we will hit this issue and we need to figure out some solution.

**Comment by Thirumalai-Shaktivel** [comment]
https://github.com/lfortran/lfortran/pull/1045#issuecomment-1445146225

Got it, thank you.

**Comment by certik** [comment]
I added two more TODO items for this PR before we can merge.

**Comment by Thirumalai-Shaktivel** [comment]
By "wrapper" you mean: I need to create a function, check for arguments, and ...
Can you please explain more about this implementation?

File: src/libasr/pass/intrinsic_function.cpp [hunk 6]
```diff
@@ -0,0 +1,167 @@
...
+};
+
+void pass_replace_intrinsic_function(Allocator &al, ASR::TranslationUnit_t &unit,
+                             const LCompilers::PassOptions& /*pass_options*/) {
+    ReplaceIntrinsicFunctionVisitor v(al, unit.m_global_scope);
+    v.visit_TranslationUnit(unit);
+}
+
+
+} // namespace LCompilers
```
Comment (czgdp1807) [inline src/libasr/pass/intrinsic_function.cpp:167]: So this pass basically replaces only `log_gamma` for now, correct? However I guess we would want to replace any `IntrinsicFunction` with the call to its actual implementation function and add that implementation function in the global scope. That's where we need some scalable design, correct? I guess that's what we discussed in our last meeting @certik. If so then I would do it Tuesday next week, once this PR is merged by then.

Comment (certik) [reply src/libasr/pass/intrinsic_function.cpp:167]: > So this pass basically replaces only log_gamma for now, correct? 

Yes.

> However I guess we would want to replace any IntrinsicFunction with the call to its actual implementation function and add that implementation function in the global scope.

Yes.

> That's where we need some scalable design, correct?

Yes.

> I guess that's what we discussed in our last meeting @certik.

Yes.

> If so then I would do it Tuesday next week, once this PR is merged by then.

Perfect.

**Comment by certik** [comment]
> By "wrapper" you mean: I need to create a function, check for arguments, and ...
> Can you please explain more about this implementation?

It's the implementation in this PR before the commit [Use BindC to compute the values for IntrinsicFunctions](https://github.com/lfortran/lfortran/pull/1045/commits/0cf67f2ea1ff82666936026b5cc1813c9eefb672), so here is how it looks like:

https://github.com/lfortran/lfortran/blob/4b2b9febd5d292b9034ba3b4f317196148b3fc72/src/libasr/pass/intrinsic_function.cpp#L35

So we already have it. All we need is not to replace this:
```
    // TODO: Call the C implementation of LogGamma using BindC
    body.push_back(al, ASRUtils::STMT(ASR::make_Assignment_t(al, loc,
        ASRUtils::EXPR(ASR::make_Var_t(al, loc, return_var)),
        ASRUtils::EXPR(ASR::make_Var_t(al, loc, arg)), nullptr)));
```
with a FunctionCall to the C implementation. 

What you have done is that you have replaced the whole wrapper with the C call, but now we will keep the wrapper and just replace the dummy/temporary assignment with the C call.

Let me know if it makes sense.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, at first I thought to do the same. But, for a FunctionCall we need a symbol, right? How do I get that symbol from C implementation?

**Comment by certik** [comment]
I would use the exact symbol that you currently have there in this PR: https://github.com/lfortran/lfortran/blob/deb94ec52f5f944fab4e085a897edfe71ee96dbb/src/libasr/pass/intrinsic_function.cpp#L67, just call it.

File: integration_tests/intrinsics_19.f90 [hunk 7]
```diff
@@ -57,10 +59,16 @@ program intrinsics_19
...
 print *, log10(0.5), log10(0.5_dp), s10, d10, log10(x), log10(y)
 print *, nint(3.6), nint(3.6_dp), s11, d11, nint(x2), nint(y2)
 print *, floor(3.6), floor(3.6_dp), s12, d12, floor(x2), floor(y2)
 print *, nint(-3.6), nint(-3.6_dp), s13, d13, nint(-x2), nint(-y2)
 print *, floor(-3.6), floor(-3.6_dp), s14, d14, floor(-x2), floor(-y2)
 if (abs(dsqrt(4.0_dp) - 2.0_dp) > 1e-15_dp) error stop
-end
+
+if (abs(s9_ - log_gamma(log_gamma(x) + 3*log_gamma(x+log_gamma(x)))) > 1e-7) error stop
+if (abs(d9_ - log_gamma(log_gamma(y) + 3*log_gamma(y+log_gamma(y)))) > 1e-15_dp) error stop
```
Comment (certik) [inline integration_tests/intrinsics_19.f90:72]: In addition, also add:
```fortran
if (abs(d9_ - 0.3452345) > 1e-15_dp) error stop
```
Change the reference value 0.3452345 to the actual correct value. That way we ensure it works, as in your code above, it could happen that both `d9_` and the expression on the right return the same wrong answer.

**Comment by certik** [comment]
I think we have it! I played with it locally, it seems to work as expected.

**Comment by certik** [comment]
I cleaned up the commits in https://github.com/lfortran/lfortran/pull/1371.

**Comment by certik** [comment]
The follow up improvements are listed in https://github.com/lfortran/lfortran/issues/1372.
