### ISSUE TITLE
OpenMP: with --separate-compilation, outlined region names collide at link time (duplicate symbol _lcompilers_parallel_func1)

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#13064]
With `--separate-compilation`, a module procedure with two OpenMP regions, compiled separately from the program that uses it, fails to link: `duplicate symbol '_lcompilers_parallel_func1'`. The first outlined function gets a unique hashed name (`_lcompilers_parallel_func_<hash>`), but the second one is emitted as plain `_lcompilers_parallel_func1`. Both object files define it, the module's and the program's, even though the program has no OpenMP region. Without `--separate-compilation` the same files compile, link and print `110`. gfortran with `-fopenmp` prints `110` with 1 and 4 threads.

## Reproducer

`sc2_mod.f90`:

```fortran
module sc2_mod
implicit none
contains
subroutine work(x)
  integer, intent(out) :: x
  integer :: a(10), i
  !$omp parallel do
  do i = 1, 10
    a(i) = i
  end do
  !$omp end parallel do
  !$omp parallel do
  do i = 1, 10
    a(i) = 2*a(i)
  end do
  !$omp end parallel do
  x = sum(a)
end subroutine
end module
```

`sc2_main.f90`:

```fortran
program sc2_main
use sc2_mod, only: work
implicit none
integer :: x
call work(x)
if (x /= 110) error stop 1
print *, x
end program
```

```
lfortran --openmp --separate-compilation -c sc2_mod.f90
lfortran --openmp --separate-compilation -c sc2_main.f90
lfortran --openmp --openmp-lib-dir=$CONDA_PREFIX/lib --separate-compilation sc2_mod.o sc2_main.o -o a.out
```

## Actual

The link step exits with code 10:

```
duplicate symbol '_lcompilers_parallel_func1' in:
    sc2_mod.o
    sc2_main.o
ld: 1 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`nm` shows:

```
sc2_mod.o:
T _lcompilers_parallel_func1
T _lcompilers_parallel_func_XpRZH8KtbrBu90ya4Ss8i0
sc2_main.o:
T _lcompilers_parallel_func1
T _lcompilers_parallel_func_p79UZsC1Eq5DYGyzbNgZWN
```

## Expected

The program should link and print `110`, as it does without `--separate-compilation` and with `gfortran -std=f2018 -fopenmp` (1 and 4 threads). Every name generated for an outlined region should be unique across object files, and a program with no region should not define them.

Found while working on #12862 (#12855). Tested with LFortran at 73d6301695, where it fails as above. At 1afa3cdc33 it fails earlier, with #12910's verify error. The original reproducer (a module with a `parallel do` and a `parallel reduction` region, `use omp_lib`) also fails to link with the same duplicate symbol on #12862's branch.
