### ISSUE TITLE
null() as the initializer of a non-pointer, non-allocatable variable or component is accepted: silent compile or LLVM crash

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#13107]
`null()` is not a valid initializer for an entity that is neither a pointer nor allocatable. LFortran has no semantic check for this in a declaration or a component default. Depending on the entity, it compiles silently or crashes in LLVM codegen. gfortran and flang reject it. #13055 was the same problem for a structure constructor argument; this is the declaration-initializer case.

## Reproducer 1: variable (compiles silently)

```fortran
program main
implicit none
integer :: i = null()
print *, i
end program
```

```console
$ lfortran b2_int.f90 && ./a.out
0
```

`type(c_ptr) :: q = null()` also compiles silently, and so does a component default `type(c_ptr) :: p = null()`:

```fortran
program main
use iso_c_binding, only: c_ptr
implicit none
type :: w_t
    integer :: h = 0
    type(c_ptr) :: p = null()
end type
type(w_t) :: v
print *, v%h
end program
```

## Reproducer 2: integer component default (LLVM crash)

```fortran
program main
implicit none
type :: w_t
    integer :: h = 0
    integer :: k = null()
end type
type(w_t) :: v
print *, v%h
end program
```

```console
$ lfortran b2_comp_int.f90
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 269.
Traceback (most recent call last):
  File "src/bin/lfortran.cpp", line 3067
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "src/lfortran/pipeline.cpp", line 78
    evaluator.get_llvm3(asr, pass_manager, diagnostics, lm, infile,
  ...
```

LFortran commit 73d6301695.

## gfortran 16.1

```console
$ gfortran b2_int.f90
b2_int.f90:3:14:
    3 | integer :: i = null()
      |              1
Error: NULL appears on right-hand side in assignment at (1)
```

gfortran reports the same error for the `type(c_ptr)` variable and for both component defaults.

## flang 22

```console
$ flang b2_int.f90
error: Semantic errors in b2_int.f90
./b2_int.f90:3:16: error: NULL() may not be used as an expression in this context
  integer :: i = null()
                 ^^^^^^
./b2_int.f90:3:16: error: Initialization expression cannot be converted to declared type of 'i'
```

flang reports the same errors for the other cases.

Found while fixing the c_null_ptr constructor regression from #13048
